from src.schemas import DeepAnalState


def grounding(state: DeepAnalState): ...
def collector(state: DeepAnalState): ...
def curator(state: DeepAnalState): ...
def briefer(state: DeepAnalState): ...
def editor(state: DeepAnalState): ...
