from src.schemas import DeepAnalState


def financial_analyst(state: DeepAnalState): ...
def industry_analyst(state: DeepAnalState): ...
def company_analyst(state: DeepAnalState): ...
def news_analyst(state: DeepAnalState): ...
def risk_analyst(state: DeepAnalState): ...
